name: Bennie Robinson
highlighter: rouge
url: https://bennierobinson.com
paginate: 100

plugins:
  - jekyll-paginate
  - jekyll-archives

webrick:
  headers:
    "X-Frame-Options": "DENY"

jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tag: "/tag/:name/"
