name: Bennie Robinson
highlighter: rouge
url: https://bennierobinson.com
paginate: 100

plugins:
  - jekyll-paginate
  - jekyll-archives

webrick:
  headers:
    "X-Frame-Options": "DENY"

jekyll-archives:
  enabled: all
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: tag-archive
    category: tag-archive
